https://github.com/chiphuyen/tf-stanford-tutorials

a1_q1_exercises.py

In [6]:
"""
Simple TensorFlow exercises
You should thoroughly test your code
"""

import tensorflow as tf

###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.less(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

0.49760592

In [11]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_shuffle([-1, 1])[0]
y = tf.random_shuffle([-1, 1])[0]

f1 = lambda: tf.add(x, y)
f2 = lambda: tf.subtract(x, y)
f3 = lambda: tf.constant(0)

out = tf.case({tf.less(x, y): f1, tf.greater(x, y): f2}, default = f3, exclusive = True)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

0

In [12]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)

out = tf.equal(x, y)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

array([[ True, False, False],
       [ True, False, False]], dtype=bool)

In [34]:
""" Help on this exercise. """

###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])
y = tf.range(20)
z = tf.fill(tf.shape(x), 30.0)
p = tf.fill(tf.shape(x), -1.0)

out1 = tf.where(tf.greater(x, z), tf.to_float(y), p)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out1.eval()

array([ -1.,  -1.,   2.,  -1.,   4.,  -1.,   6.,  -1.,   8.,   9.,  -1.,
        11.,  -1.,  -1.,  14.,  -1.,  16.,  -1.,  18.,  -1.], dtype=float32)

In [36]:
###############################################################################
# 1e: Create a diagonal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

diag = tf.diag(tf.range(1,7))

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
diag.eval()

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]], dtype=int32)

In [40]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

x = tf.random_normal([10, 10], 0, 1)

out = tf.matrix_determinant(x)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

338.69733

In [42]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])

out = tf.unique(x)[0]

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32)

In [58]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.less() and tf.select() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

n = tf.constant(300) # Length of x and y

x = tf.random_normal([n], 0, 1)
y = tf.random_normal([n], 0, 1)

avg = tf.divide(tf.reduce_sum(tf.subtract(x, y)), tf.to_float(n))

f1 = lambda: tf.divide(tf.reduce_sum(tf.pow(tf.subtract(x, y), 2)), tf.to_float(n))
f2 = lambda: tf.reduce_sum(tf.abs(tf.subtract(x, y)))

out = tf.cond(tf.less(avg, tf.constant(0.0)), f1, f2)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
out.eval()

1.9476779